openapi: 3.0.0
info:
  title: assignment API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
paths:
  /assignments:
    get:
      tags:
        - default
      summary: Get all assignments
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Add assignment valid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                subject: English
                assignment: Proposal
                due_date: '2021-10-20'
                id: 2
                done: 'false'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /assignments/1:
    delete:
      tags:
        - default
      summary: Delete Assignment
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /assignments/done/2:
    put:
      tags:
        - default
      summary: Mark as done
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /assignments/undone/2:
    put:
      tags:
        - default
      summary: Mark as not done
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}